name: PR Validation
on:
  pull_request:
    branches:
      - develop
    types:
      - opened
      - synchronize
jobs:
  lint:
    name: Lint HTML and CSS Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Lint HTML Files
        run: |
          echo "Linting HTML files..."
          npx htmlhint "src/pages/*/.html"
          echo "HTML linting completed successfully"

      - name: Lint CSS Files
        run: |
            echo "Linting CSS files with basic rules..."
            if find styles -name "*.css" | grep -q .; then
              npx stylelint "src/css/*/.css"
              echo "CSS linting completed successfully"  
            else
              echo "No CSS files found to lint"
            fi
# Job 2
  build:
    name: Build Website
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test Building With Parcel
        run: npx parcel build ".src/pages/index.html" --dist-dir "./dist" --public-url "./"