name: PR Validation for Develop Branch

on:
  pull_request:
    branches: [develop]

jobs:
  lint-and-build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install Dependencies
        run: npm install

      - name: Run HTMLHint
        run: npx htmlhint '**/*.html'

      - name: Run Stylelint
        run: npx stylelint "**/*.css"

      - name: Parcel Build
        run: npx parcel build src/index.html
