name: Release CI

on:
  pull_request:
    branches:
      - release
    types:
      - opened
      - synchronize

jobs:
  lint:
    name: Lint HTML and CSS Files
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run HTMLHint
        run: |
            echo "Linting HTML files..."
            npx htmlhint "src/pages/**/*.html" --config .htmlhintrc.json
            echo "HTML linting completed successfully"

      - name: Run Stylelint
        run: |
            echo "Linting CSS files..."
            if find src/css -name "*.css" | grep -q .; then
              npx stylelint "src/css/**/*.css" --config .stylelintrc.json
              echo "CSS linting completed successfully"  
            else
              echo "No CSS files found to lint"
            fi
# Job 2
  build:
    name: Build Website
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Test Building With Parcel
        run: npx parcel build "./src/index.html" --dist-dir "./dist" --public-url "./"
        